// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBifTDIshaUWOl8kDIdWoOknkpS6z-ScTI',
    appId: '1:930853487400:web:ea26d2cb5cffa4c73dc61d',
    messagingSenderId: '930853487400',
    projectId: 'projeto-ic-ufrn',
    authDomain: 'projeto-ic-ufrn.firebaseapp.com',
    storageBucket: 'projeto-ic-ufrn.appspot.com',
    measurementId: 'G-ZT9X7DF0HJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDGJayc8ppN1hCUDOqQ2ShtqX9q3uI7Uw',
    appId: '1:930853487400:android:fb8ef55d537b288f3dc61d',
    messagingSenderId: '930853487400',
    projectId: 'projeto-ic-ufrn',
    storageBucket: 'projeto-ic-ufrn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa4Ec8GqeWVncZQq3k--CcUA_Ial1ztcQ',
    appId: '1:930853487400:ios:2d1e6f6b2170991a3dc61d',
    messagingSenderId: '930853487400',
    projectId: 'projeto-ic-ufrn',
    storageBucket: 'projeto-ic-ufrn.appspot.com',
    iosClientId: '930853487400-73maifksobdjoh3dkmtemrf5ovgj46qr.apps.googleusercontent.com',
    iosBundleId: 'com.example.aqualyze',
  );
}
